# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160229_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
